name: Development

on:
  push:

jobs:
  # Lint repo
  lint:
    name: 'Lint'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm run lint

  # Run Unit Tests
  unit-test:
    name: 'Unit Tests'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm run unit-test

  # Run End to End tests
  # e2e-test:
  #   name: 'End-to-End Tests'
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - run: npm ci
  #     - run: npm run e2e-test

  # Generate documentation
  # documentation:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - run: npm i
  #     - run: npm run doc
  
  # folder:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: mkdir out  

  document:
    name: "crazy doc"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install JSDoc
        run: npm install -g jsdoc
      - name: Generate JSDoc
        run: jsdoc -r src
      - name: List files in current directory
        run: ls

