name: Development

on:
  push:

jobs:
  # Lint repo
  lint:
    name: 'Lint'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm run lint

  # Run Unit Tests
  unit-test:
    name: 'Unit Tests'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm run unit-test

  # Run End to End tests
  e2e-test:
    name: 'End-to-End Tests'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - name: Install Dependencies
        uses: actions/setup-node@v2
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'true'
        with:
      - name: Puppeteer Headful
        uses: mujo-code/puppeteer-headful@18.9.0
      - run: npm run e2e-test

  # Generate documentation
  documentation:
    runs-on: ubuntu-latest
    needs: [unit-test, e2e-test]
    steps:
      - uses: actions/checkout@v3
      - run: npm i
      - run: npm run doc
      - run: ls
      - run: |
          git config --global user.name "JSDoc_Generator"
          git add --all
          git commit -m "Generate JSdoc"
          git push
