name: Documentation

on:
  push:
  # workflow_run:
  #   workflows: ['Development']
  #   branches: '!main'
  #   types:
  #     - completed

jobs:
  documentation:
    name: 'Documentation'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm run doc
      - run: git add .
      - run: git commit -am "Updated documentation"
      - run: git push
